version: "3.9"

services:
  # go_app:
  #   container_name: go_app
  #   image: gin_boilerplate
  #   environment:
  #     REDIS_HOST: redis:6379
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis
  #     - go_db
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
